import { CategoryTab, DetailedTestItem, TestContextIds } from './test-services.types';

export const EAP_CATEGORIES: CategoryTab[] = [
  { key: 'ALL', label: 'All EAP APIs', icon: 'ph-squares-four' },
  { key: 'GENERAL', label: 'General Info & Apps', icon: 'ph-article' },
  { key: 'STUDY_TEAM', label: 'Study Team & Orgs', icon: 'ph-users-three' },
  { key: 'MILESTONES', label: 'Milestones & Reports', icon: 'ph-flag' },
  { key: 'REQUESTS', label: 'Requests & Amendments', icon: 'ph-git-pull-request' }
];

export function getEapTestItems(context: TestContextIds): DetailedTestItem[] {
  return [
    // ==================== 1. GENERAL INFO & APPLICATIONS ====================
    {
      id: 'EAP-GEN-1',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get Applications List',
      endpoint: 'api/EAPGeneralInfo/GetApplicationsList',
      method: 'POST',
      payload: { Status: 'ALL', PageIndex: 1, PageSize: 10 },
      expectedData: 'Array of EAP applications',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-2',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Summary Search Applications',
      endpoint: 'api/EAPGeneralInfo/getSummarySearch',
      method: 'POST',
      payload: { SearchText: '', Status: '-1' },
      expectedData: 'Filtered applications summary list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-3',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get Master Dropdown Data',
      endpoint: 'api/EAPGeneralInfo/GetMasterList?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Master dropdowns for EAP general form',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-4',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get My Applications List',
      endpoint: 'api/EAPMyApplications/GetMyApplicationsList',
      method: 'POST',
      payload: { PageIndex: 1, PageSize: 10 },
      expectedData: 'User-specific EAP applications',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-5',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Search My Applications',
      endpoint: 'api/EAPMyApplications/getMySummarySearch',
      method: 'POST',
      payload: { SearchText: '' },
      expectedData: 'Filtered personal applications',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-6',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get Application Change Log',
      endpoint: 'api/EAPGeneralInfo/GetApp_ChangeLog?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Audit change log history',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-7',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Validate Application Submission',
      endpoint: 'api/EAPGeneralInfo/EAP_APPSubmitValidation?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Submission validation status or error list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-8',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Insert EAP General Info',
      endpoint: 'api/EAPGeneralInfo/Insert',
      method: 'POST',
      payload: { APPLICATION_NAME: 'EAP Trial Protocol Alpha', STATUS: '1' },
      expectedData: 'Created general info record ID',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-9',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Update EAP General Info',
      endpoint: 'api/EAPGeneralInfo/Update',
      method: 'POST',
      payload: { APPLICATION_ID: '1', APPLICATION_NAME: 'EAP Trial Protocol Alpha (Updated)' },
      expectedData: 'Updated general info confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-GEN-10',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Insert Organization Mapping',
      endpoint: 'api/EAPOrganization/Insert',
      method: 'POST',
      payload: { APPLICATION_ID: '1', ORGANIZATION_ID: '1' },
      expectedData: 'Saved organization association',
      status: 'IDLE',
      matched: false
    },

    // ==================== 2. STUDY TEAM & ORGANIZATIONS ====================
    {
      id: 'EAP-STM-1',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Get Study Team Master Data',
      endpoint: 'api/EAPStudyTeam/GetMasterData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Master roles & org dropdowns for study team',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-2',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Search Study Team Master Data',
      endpoint: 'api/EAPStudyTeam/GetMasterDataSearch?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Search master records for study team',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-3',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Get Study Team Summary Data',
      endpoint: 'api/EAPStudyTeam/GetSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of study team members',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-4',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Search Study Team Members',
      endpoint: 'api/EAPStudyTeam/GetSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered study team member records',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-5',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Edit Study Team Member',
      endpoint: 'api/EAPStudyTeam/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study team record details for editing',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-6',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Insert Study Team Member',
      endpoint: 'api/EAPStudyTeam/Insert',
      method: 'POST',
      payload: { ApplicationID: '1', USER_NAME: 'Dr. Jane Smith', ROLE_ID: '1' },
      expectedData: 'Created study team member confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-7',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Update Study Team Member',
      endpoint: 'api/EAPStudyTeam/Update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', USER_NAME: 'Dr. Jane Smith', ROLE_ID: '1' },
      expectedData: 'Updated study team confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-8',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Get Review Board Data',
      endpoint: 'api/EAPReviewBoard/GetSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Review board / IRB details for application',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-9',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Insert Review Board',
      endpoint: 'api/EAPReviewBoard/Insert',
      method: 'POST',
      payload: { ApplicationID: '1', BOARD_NAME: 'Ethics Review Committee' },
      expectedData: 'Created review board record',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-STM-10',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Orgs',
      apiName: 'Update Review Board',
      endpoint: 'api/EAPReviewBoard/Update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', BOARD_NAME: 'Ethics Committee' },
      expectedData: 'Updated review board record',
      status: 'IDLE',
      matched: false
    },

    // ==================== 3. MILESTONES & REPORTS ====================
    {
      id: 'EAP-MLS-1',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Get Milestones Summary Data',
      endpoint: 'api/EAPMilestones/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Milestone tracking list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-2',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Search Milestones Summary',
      endpoint: 'api/EAPMilestones/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered milestones list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-3',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Edit Milestone',
      endpoint: 'api/EAPMilestones/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Milestone record details for editing',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-4',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Insert Milestone',
      endpoint: 'api/EAPMilestones/Insert',
      method: 'POST',
      payload: { ApplicationID: '1', MILESTONE_NAME: 'Initial Patient Screening', STATUS: '1' },
      expectedData: 'Created milestone confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-5',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Update Milestone',
      endpoint: 'api/EAPMilestones/Update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', MILESTONE_NAME: 'Patient Screening Completed' },
      expectedData: 'Updated milestone confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-6',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Send Milestone Notification',
      endpoint: 'api/EAPMilestones/MilestoneSendNotification/1',
      method: 'GET',
      payload: null,
      expectedData: 'Notification dispatch confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-7',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Get Study Reports Summary Data',
      endpoint: 'api/EAPStudyreports/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study reports submission records',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-8',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Get Study Reports Master Data',
      endpoint: 'api/EAPStudyreports/GetMasterData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study report master dropdowns',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-9',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Search Study Reports Summary',
      endpoint: 'api/EAPStudyreports/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered study reports list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-10',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Edit Study Report',
      endpoint: 'api/EAPStudyreports/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study report record details for editing',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-11',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Insert Study Report',
      endpoint: 'api/EAPStudyreports/Insert',
      method: 'POST',
      payload: { ApplicationID: '1', REPORT_TYPE: 'Progress Report', STATUS: '1' },
      expectedData: 'Created study report confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-MLS-12',
      category: 'MILESTONES',
      categoryLabel: 'Milestones & Reports',
      apiName: 'Update Study Report',
      endpoint: 'api/EAPStudyreports/Update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', REPORT_TYPE: 'Annual Progress Report' },
      expectedData: 'Updated study report confirmation',
      status: 'IDLE',
      matched: false
    },

    // ==================== 4. REQUESTS & AMENDMENTS ====================
    {
      id: 'EAP-REQ-1',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Get Requests Summary Master',
      endpoint: 'api/EAPAllRequests/GetSummaryMaster?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Requests summary master metadata',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-2',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Get Requests Summary Data',
      endpoint: 'api/EAPAllRequests/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Summary of drug / fund requests',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-3',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Search Requests Summary',
      endpoint: 'api/EAPAllRequests/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered request list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-4',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Get Product Master Drop Data',
      endpoint: 'api/EAPAllRequests/GetProductMasterDropData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Product request options',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-5',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Get Fund Master Drop Data',
      endpoint: 'api/EAPAllRequests/GetFundMasterDropData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Fund request options',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-6',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Insert Product Request',
      endpoint: 'api/EAPAllRequests/InsertProduct',
      method: 'POST',
      payload: { ApplicationID: '1', PRODUCT_ID: '1', QUANTITY: 100 },
      expectedData: 'Created product request confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-7',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Update Product Request',
      endpoint: 'api/EAPAllRequests/UpdateProduct',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', QUANTITY: 150 },
      expectedData: 'Updated product request confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-8',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Edit Product Request',
      endpoint: 'api/EAPAllRequests/EditProduct?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Product request details for editing',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-9',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Insert Fund Request',
      endpoint: 'api/EAPAllRequests/InsertFund',
      method: 'POST',
      payload: { ApplicationID: '1', AMOUNT: 25000, CURRENCY_ID: 'USD' },
      expectedData: 'Created fund request confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-10',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Update Fund Request',
      endpoint: 'api/EAPAllRequests/UpdateFund',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', AMOUNT: 30000 },
      expectedData: 'Updated fund request confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-11',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Approve Request Workflow',
      endpoint: 'api/EAPAllRequests/Approve?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Approval result confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-12',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Reject Request Workflow',
      endpoint: 'api/EAPAllRequests/Reject?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Rejection confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-13',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Allocate Request Workflow',
      endpoint: 'api/EAPAllRequests/Allocate?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Allocation confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-14',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Return Request Workflow',
      endpoint: 'api/EAPAllRequests/RequestReturn?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Return request confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-15',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Withdraw Request Workflow',
      endpoint: 'api/EAPAllRequests/WithDraw?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Withdrawal confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-16',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Close Request Workflow',
      endpoint: 'api/EAPAllRequests/Close?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Close confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'EAP-REQ-17',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Get Amendments Summary',
      endpoint: 'api/EAPAmendments/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of protocol amendments',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'EAP-REQ-18',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Get Amendments Types',
      endpoint: 'api/EAPAmendments/getTypes?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Amendment type definitions',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'EAP-REQ-19',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Search Amendments Summary',
      endpoint: 'api/EAPAmendments/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered amendments records',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'EAP-REQ-20',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Edit Amendment',
      endpoint: 'api/EAPAmendments/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Amendment record details for editing',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'EAP-REQ-21',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Insert Amendment',
      endpoint: 'api/EAPAmendments/Insert',
      method: 'POST',
      payload: { ApplicationID: '1', AMENDMENT_NAME: 'Protocol Amendment v2', REASON: 'Dosing Adjustment' },
      expectedData: 'Created amendment record',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'EAP-REQ-22',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Amendments',
      apiName: 'Update Amendment',
      endpoint: 'api/EAPAmendments/Update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', AMENDMENT_NAME: 'Protocol Amendment v2.1' },
      expectedData: 'Updated amendment record',
      status: 'PENDING',
      matched: false
    }
  ];
}
