import { CategoryTab, DetailedTestItem, TestContextIds } from './test-services.types';

export const UM_CATEGORIES: CategoryTab[] = [
  { key: 'ALL', label: 'All UM APIs', icon: 'ph-squares-four' },
  { key: 'AUDIT', label: 'Audit & Activity Logs', icon: 'ph-clock-counter-clockwise' },
  { key: 'USERS', label: 'User Operations', icon: 'ph-users' },
  { key: 'DEPT_ROLES', label: 'Departments & Roles', icon: 'ph-briefcase' },
  { key: 'ORGS', label: 'Organization Management', icon: 'ph-buildings' }
];

export function getUmTestItems(context: TestContextIds): DetailedTestItem[] {
  return [
    // ==================== 1. AUDIT & ACTIVITY LOGS ====================
    {
      id: 'UM-AUD-1',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Search SuperAdmin Audit Records',
      endpoint: 'api/SuperAdminAuditLog/GetAuditLogRecordList/',
      method: 'POST',
      payload: { Category: 'Organization', Name: '', StartDate: '', EndDate: '' },
      expectedData: 'Audit records array or response model',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-2',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get Audit Details List',
      endpoint: 'api/SuperAdminAuditLog/GetAuditLogDetailsList',
      method: 'POST',
      payload: { versionIDs: ['1'], categories: 'Organization' },
      expectedData: 'Revision field changes detail',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-3',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get Audit Revision History',
      endpoint: 'api/SuperAdminAuditLog/GetAuditLogRevisionList?RelatedPkId=1&CatergoryType=Organization',
      method: 'GET',
      payload: null,
      expectedData: 'Array of historical revisions',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-4',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Search IEG Activity Logs',
      endpoint: 'api/IEGAuditActivityLogs/GetIEGActivityLogSearch',
      method: 'POST',
      payload: { ModuleName: 'IST', PageIndex: 1, PageSize: 10 },
      expectedData: 'Activity log records list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-5',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get Activity Log By App ID',
      endpoint: 'api/IEGAuditActivityLogs/GetIEGActivityLogByApplicationId?ApplicationId=1',
      method: 'GET',
      payload: null,
      expectedData: 'Timeline of activities for application',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-6',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get Multi-Summary Activity Logs',
      endpoint: 'api/IEGAuditActivityLogs/GetIEGAuditLogMultiSummary',
      method: 'POST',
      payload: { ModuleName: 'IST' },
      expectedData: 'Multi-criteria activity summary dataset',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-7',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get All Organization Users For Logs',
      endpoint: 'api/IEGAuditActivityLogs/GetAllOrgUsersList?ModuleName=IST',
      method: 'GET',
      payload: null,
      expectedData: 'List of users who triggered activities',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-8',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get Application IDs For Logs',
      endpoint: 'api/IEGAuditActivityLogs/GetApplicationIdsList?ModuleName=IST',
      method: 'GET',
      payload: null,
      expectedData: 'Application identifiers list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-9',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get Grant Types For Logs',
      endpoint: 'api/IEGAuditActivityLogs/GetGrantTypes?ModuleName=GM',
      method: 'GET',
      payload: null,
      expectedData: 'Grant types array',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-AUD-10',
      category: 'AUDIT',
      categoryLabel: 'Audit & Activity Logs',
      apiName: 'Get Screen Names For Logs',
      endpoint: 'api/IEGAuditActivityLogs/GetScreenNameList?ModuleName=IST',
      method: 'GET',
      payload: null,
      expectedData: 'Screen names list',
      status: 'PENDING',
      matched: false
    },

    // ==================== 2. USERS ====================
    {
      id: 'UM-USR-1',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Get User Summary List',
      endpoint: 'api/appuser/getusers/-1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of users in system',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-2',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Get User Search Master Data',
      endpoint: 'api/appuser/getusersearchmaster',
      method: 'GET',
      payload: null,
      expectedData: 'Master dropdowns for user filtering',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-3',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Advanced User Search',
      endpoint: 'api/appuser/getadvsearch',
      method: 'POST',
      payload: { USER_NAME: '', STATUS: '-1' },
      expectedData: 'Filtered users list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-4',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Get Internal Users List',
      endpoint: 'api/appuser/getinternalusers',
      method: 'GET',
      payload: null,
      expectedData: 'Array of internal system users',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-5',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Get User Details By ID',
      endpoint: 'api/appuser/getuserbyid/1',
      method: 'GET',
      payload: null,
      expectedData: 'User profile model',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-6',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Get Support User By ID',
      endpoint: 'api/appuser/getsupportuserbyid/1',
      method: 'GET',
      payload: null,
      expectedData: 'Support user details',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-7',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Insert User',
      endpoint: 'api/User/insert',
      method: 'POST',
      payload: { USER_NAME: 'test.developer', EMAIL: 'test.developer@ieg.com', STATUS: '1' },
      expectedData: 'Created user confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-8',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Update User',
      endpoint: 'api/User/update',
      method: 'POST',
      payload: { USER_ID: '1', USER_NAME: 'test.developer', STATUS: '1' },
      expectedData: 'Updated user confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-9',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Delete User',
      endpoint: 'api/User/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete user confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-10',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Add User Roles',
      endpoint: 'api/User/adduserroles',
      method: 'POST',
      payload: { USER_ID: '1', ROLE_IDS: ['1'] },
      expectedData: 'Assigned roles confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-USR-11',
      category: 'USERS',
      categoryLabel: 'User Operations',
      apiName: 'Add Support User',
      endpoint: 'api/supportuser/addsupportuser',
      method: 'POST',
      payload: { USER_NAME: 'support.lead', EMAIL: 'support.lead@ieg.com' },
      expectedData: 'Created support user confirmation',
      status: 'PENDING',
      matched: false
    },

    // ==================== 3. DEPARTMENTS & ROLES ====================
    {
      id: 'UM-DPT-1',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Get Departments List',
      endpoint: 'api/department/getdepartments/-1/-1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of active departments',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-DPT-2',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Advanced Department Search',
      endpoint: 'api/department/getadvsearch',
      method: 'POST',
      payload: { CODE: '', NAME: '', STATUS: '-1' },
      expectedData: 'Filtered departments array',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-DPT-3',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Insert Department',
      endpoint: 'api/Department/insert',
      method: 'POST',
      payload: { CODE: 'CLIN-DEV', NAME: 'Clinical Development', STATUS: '1' },
      expectedData: 'Created department confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-DPT-4',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Update Department',
      endpoint: 'api/Department/update',
      method: 'POST',
      payload: { DEPT_ID: '1', CODE: 'CLIN-DEV', NAME: 'Clinical Development Operations' },
      expectedData: 'Updated department confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-DPT-5',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Delete Department',
      endpoint: 'api/Department/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete department confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ROL-1',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Get Roles List',
      endpoint: 'api/role/getroles/-1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of system roles',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ROL-2',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Advanced Role Search',
      endpoint: 'api/role/getadvsearch',
      method: 'POST',
      payload: { ROLE_NAME: '', STATUS: '-1' },
      expectedData: 'Filtered roles dataset',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ROL-3',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Get System Modules For Permissions',
      endpoint: 'api/role/getmodules',
      method: 'GET',
      payload: null,
      expectedData: 'Modules list for permission matrix',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ROL-4',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Insert Role',
      endpoint: 'api/role/insert',
      method: 'POST',
      payload: { ROLE_NAME: 'Clinical Reviewer', STATUS: '1' },
      expectedData: 'Created role confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ROL-5',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Update Role',
      endpoint: 'api/role/update',
      method: 'POST',
      payload: { ROLE_ID: '1', ROLE_NAME: 'Senior Clinical Reviewer' },
      expectedData: 'Updated role confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ROL-6',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Delete Role',
      endpoint: 'api/role/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete role confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ROL-7',
      category: 'DEPT_ROLES',
      categoryLabel: 'Departments & Roles',
      apiName: 'Insert Role Privilege',
      endpoint: 'api/roleprivilege/insert',
      method: 'POST',
      payload: { ROLE_ID: '1', MODULE_ID: '1', PRIVILEGE_ID: '1' },
      expectedData: 'Saved privilege mapping',
      status: 'PENDING',
      matched: false
    },

    // ==================== 4. ORGANIZATIONS ====================
    {
      id: 'UM-ORG-1',
      category: 'ORGS',
      categoryLabel: 'Organization Management',
      apiName: 'Get Organizations List',
      endpoint: 'api/organization/getorganizatoins',
      method: 'GET',
      payload: null,
      expectedData: 'Array of organizations',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ORG-2',
      category: 'ORGS',
      categoryLabel: 'Organization Management',
      apiName: 'Advanced Organization Search',
      endpoint: 'api/organization/getadvsearch',
      method: 'POST',
      payload: { NAME: '', STATUS: '-1' },
      expectedData: 'Filtered organizations list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ORG-3',
      category: 'ORGS',
      categoryLabel: 'Organization Management',
      apiName: 'Get Orgs For Storage',
      endpoint: 'api/appuser/GetOrgsForStorage/DEFAULT',
      method: 'GET',
      payload: null,
      expectedData: 'Storage mapping metadata for org',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ORG-4',
      category: 'ORGS',
      categoryLabel: 'Organization Management',
      apiName: 'Insert Organization',
      endpoint: 'api/organization/insert',
      method: 'POST',
      payload: { CODE: 'ORG-APEX', NAME: 'Apex Therapeutics Inc', STATUS: '1' },
      expectedData: 'Created organization confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ORG-5',
      category: 'ORGS',
      categoryLabel: 'Organization Management',
      apiName: 'Update Organization',
      endpoint: 'api/organization/update',
      method: 'POST',
      payload: { ORGANIZATION_ID: '1', CODE: 'ORG-APEX', NAME: 'Apex Therapeutics Global Inc' },
      expectedData: 'Updated organization confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'UM-ORG-6',
      category: 'ORGS',
      categoryLabel: 'Organization Management',
      apiName: 'Delete Organization',
      endpoint: 'api/organization/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete organization confirmation',
      status: 'PENDING',
      matched: false
    }
  ];
}
