import { CategoryTab, DetailedTestItem, TestContextIds } from './test-services.types';

export const GRANTS_CATEGORIES: CategoryTab[] = [
  { key: 'ALL', label: 'All Grants APIs', icon: 'ph-squares-four' },
  { key: 'GENERAL', label: 'General Info & Audience', icon: 'ph-article' },
  { key: 'SPONSOR', label: 'Sponsors & Signees', icon: 'ph-users' },
  { key: 'BUDGET', label: 'Budget & Fund Categories', icon: 'ph-currency-circle-dollar' },
  { key: 'STUDY_TEAM', label: 'Study Team & Milestones', icon: 'ph-users-three' }
];

export function getGrantsTestItems(context: TestContextIds): DetailedTestItem[] {
  return [
    // ==================== 1. GENERAL INFO & AUDIENCE ====================
    {
      id: 'GRT-GEN-1',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Get My Applications List',
      endpoint: 'api/gmmyapplications/GetMyApplicationsList',
      method: 'POST',
      payload: { PageIndex: 1, PageSize: 10 },
      expectedData: 'Array of user grants applications',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-2',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Search My Applications',
      endpoint: 'api/gmmyapplications/getMySummarySearch',
      method: 'POST',
      payload: { SearchText: '' },
      expectedData: 'Filtered grants applications list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-3',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Get Audience Summary',
      endpoint: 'api/gmaudience/fetchsummary/1',
      method: 'GET',
      payload: null,
      expectedData: 'Target audience summary for grant',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-4',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Search Audience Advance Summary',
      endpoint: 'api/gmaudience/fetchsummaryadv',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered target audience records',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-5',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Get Audience Lookup List',
      endpoint: 'api/gmaudience/getlookuplist',
      method: 'GET',
      payload: null,
      expectedData: 'Audience dropdown options',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-6',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Insert Audience',
      endpoint: 'api/gmaudience/insert',
      method: 'POST',
      payload: { ApplicationID: '1', AUDIENCE_TYPE_ID: '1', COUNT: 100 },
      expectedData: 'Created audience record ID',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-7',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Update Audience',
      endpoint: 'api/gmaudience/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', COUNT: 150 },
      expectedData: 'Updated audience record confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-8',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Delete Audience',
      endpoint: 'api/gmaudience/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete audience confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-9',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Get Delivery Format List',
      endpoint: 'api/gmdeliveryformat/getdeliveryformat',
      method: 'GET',
      payload: null,
      expectedData: 'Grant delivery format options',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-10',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Get Therapeutic Area List',
      endpoint: 'api/gmdeliveryformat/gettherapeuticarealist',
      method: 'GET',
      payload: null,
      expectedData: 'Therapeutic area category options',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-11',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Insert Delivery Format',
      endpoint: 'api/gmdeliveryformat/insertdeliveryformat',
      method: 'POST',
      payload: { ApplicationID: '1', DELIVERY_FORMAT_ID: '1' },
      expectedData: 'Created delivery format confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-12',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Get Assessment Summary',
      endpoint: 'api/gmassessment/fetchsummary?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of educational assessments',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-13',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Insert Assessment',
      endpoint: 'api/gmassessment/insert',
      method: 'POST',
      payload: { ApplicationID: '1', ASSESSMENT_TYPE: 'Pre-Test', STATUS: '1' },
      expectedData: 'Created assessment confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-14',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Update Assessment',
      endpoint: 'api/gmassessment/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', ASSESSMENT_TYPE: 'Post-Test' },
      expectedData: 'Updated assessment confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-15',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Delete Assessment',
      endpoint: 'api/gmassessment/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete assessment confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-16',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Edit CME Application',
      endpoint: 'api/GMAPPCME/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'CME application details for editing',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-17',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Insert CME Application',
      endpoint: 'api/GMAPPCME/Insert',
      method: 'POST',
      payload: { APPLICATION_NAME: 'CME Educational Symposium 2026', STATUS: '1' },
      expectedData: 'Created CME application confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-GEN-18',
      category: 'GENERAL',
      categoryLabel: 'General Info & Audience',
      apiName: 'Update CME Application',
      endpoint: 'api/GMAPPCME/Update',
      method: 'POST',
      payload: { RecordID: '1', APPLICATION_NAME: 'CME Symposium 2026 (Updated)' },
      expectedData: 'Updated CME application confirmation',
      status: 'IDLE',
      matched: false
    },

    // ==================== 2. SPONSORS & SIGNEES ====================
    {
      id: 'GRT-SPN-1',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Get Sponsors Summary',
      endpoint: 'api/gmspons/fetchsummary?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of funding sponsors for grant',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-2',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Search Sponsors Advance Summary',
      endpoint: 'api/gmspon/fetchadvsummary',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered sponsors list',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-3',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Get Sponsor Master Data',
      endpoint: 'api/gmspon/getmasterdata?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Sponsor form dropdowns',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-4',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Get Signee by ID',
      endpoint: 'api/gmspon/getsignee/1',
      method: 'GET',
      payload: null,
      expectedData: 'Authorized signee record',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-5',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Insert Sponsor',
      endpoint: 'api/gmspon/insert',
      method: 'POST',
      payload: { ApplicationID: '1', SPONSOR_NAME: 'Global Health Fund', STATUS: '1' },
      expectedData: 'Created sponsor confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-6',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Update Sponsor',
      endpoint: 'api/gmspon/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', SPONSOR_NAME: 'Global Health Fund Inc' },
      expectedData: 'Updated sponsor confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-7',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Delete Sponsor',
      endpoint: 'api/gmspon/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete sponsor confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-8',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Make Default Sponsor',
      endpoint: 'api/gmspon/makedefault/1',
      method: 'GET',
      payload: null,
      expectedData: 'Set default sponsor confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-9',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Update Signee',
      endpoint: 'api/GMSignee/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', SIGNEE_NAME: 'Dr. Robert Miller' },
      expectedData: 'Updated signee confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-10',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Delete Signee',
      endpoint: 'api/gmsignee/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete signee confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-SPN-11',
      category: 'SPONSOR',
      categoryLabel: 'Sponsors & Signees',
      apiName: 'Make Default Signee',
      endpoint: 'api/gmsignee/makedefault/1',
      method: 'GET',
      payload: null,
      expectedData: 'Set default signee confirmation',
      status: 'IDLE',
      matched: false
    },

    // ==================== 3. BUDGET & FUND CATEGORIES ====================
    {
      id: 'GRT-BDG-1',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Get GM Budget Fund Categories',
      endpoint: 'api/gmbudget/getfundcategorylist/1/-1/USD',
      method: 'GET',
      payload: null,
      expectedData: 'List of GM budget fund categories',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-2',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Get Sponsor Budget Fund Categories',
      endpoint: 'api/sponbudget/getfundcategorylist/1/-1/USD',
      method: 'GET',
      payload: null,
      expectedData: 'List of Sponsor budget fund categories',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-3',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Get Charitable Budget Fund Categories',
      endpoint: 'api/gmcharbudget/getfundcategorylist/1/-1/USD',
      method: 'GET',
      payload: null,
      expectedData: 'List of Charitable budget fund categories',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-4',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Get GM Budget Subcategories',
      endpoint: 'api/gmbudget/getfundsubcategorylist',
      method: 'POST',
      payload: { FundCategoryId: '1' },
      expectedData: 'List of budget subcategories',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-5',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Get Sponsor Budget Summary',
      endpoint: 'api/sponbudget/fetchsummary?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Sponsor budget line items summary',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-6',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Get Sponsor Budget Total Sum',
      endpoint: 'api/sponbudget/getbudgetsum/1',
      method: 'GET',
      payload: null,
      expectedData: 'Total calculated budget amount',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-7',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Delete Sponsor Budget',
      endpoint: 'api/sponbudget/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete budget line item confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-8',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Update Sponsor Budget Status',
      endpoint: 'api/sponbudget/statusupdate/1',
      method: 'GET',
      payload: null,
      expectedData: 'Updated budget status confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-9',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Delete Charitable Budget',
      endpoint: 'api/gmcharbudget/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete charitable budget confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-10',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Update Charitable Budget Status',
      endpoint: 'api/gmcharbudget/statusupdate/1',
      method: 'GET',
      payload: null,
      expectedData: 'Updated charitable budget status confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-11',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Delete GM Budget',
      endpoint: 'api/gmbudget/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete GM budget confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-BDG-12',
      category: 'BUDGET',
      categoryLabel: 'Budget & Fund Categories',
      apiName: 'Update GM Budget Status',
      endpoint: 'api/gmbudget/statusupdate/1',
      method: 'GET',
      payload: null,
      expectedData: 'Updated GM budget status confirmation',
      status: 'IDLE',
      matched: false
    },

    // ==================== 4. STUDY TEAM & MILESTONES ====================
    {
      id: 'GRT-STM-1',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Get Study Team Summary Data',
      endpoint: 'api/gmstudyteam/getsummarydata?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of grants study team members',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-STM-2',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Search Study Team Members',
      endpoint: 'api/gmstudyteam/getsummarysearchdata',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered grants study team records',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-STM-3',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Get Study Team Master Data',
      endpoint: 'api/gmstudyteam/getmasterdata?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study team dropdown master records',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-STM-4',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Insert Study Team Member',
      endpoint: 'api/gmstudyteam/insert',
      method: 'POST',
      payload: { ApplicationID: '1', USER_NAME: 'Dr. Michael Chen', ROLE_ID: '1' },
      expectedData: 'Created study team member confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-STM-5',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Update Study Team Member',
      endpoint: 'api/gmstudyteam/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', USER_NAME: 'Dr. Michael Chen' },
      expectedData: 'Updated study team member confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-STM-6',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Delete Study Team Member',
      endpoint: 'api/gmstudyteam/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete study team member confirmation',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-STM-7',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Get Milestones Summary Data',
      endpoint: 'api/gmmilestones/getsummarydata?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Grants milestone tracking items',
      status: 'IDLE',
      matched: false
    },
    {
      id: 'GRT-STM-8',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Search Milestones Summary',
      endpoint: 'api/gmmilestones/getsummarysearchdata',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered milestones records',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'GRT-STM-9',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Insert Milestone',
      endpoint: 'api/gmmilestones/insert',
      method: 'POST',
      payload: { ApplicationID: '1', MILESTONE_NAME: 'Grant Funding Approved', STATUS: '1' },
      expectedData: 'Created milestone confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'GRT-STM-10',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Update Milestone',
      endpoint: 'api/gmmilestones/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', MILESTONE_NAME: 'Grant Funding Disbursed' },
      expectedData: 'Updated milestone confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'GRT-STM-11',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & Milestones',
      apiName: 'Delete Milestone',
      endpoint: 'api/gmmilestones/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete milestone confirmation',
      status: 'PENDING',
      matched: false
    }
  ];
}
