import { CategoryTab, DetailedTestItem, TestContextIds } from './test-services.types';

export const COMMON_CATEGORIES: CategoryTab[] = [
  { key: 'ALL', label: 'All Common APIs', icon: 'ph-squares-four' },
  { key: 'ALERTS', label: 'Alerts & Notifications', icon: 'ph-bell-ringing' },
  { key: 'CRITERIA', label: 'Screen Controls & Response', icon: 'ph-layout' },
  { key: 'REVIEW', label: 'Review Workflow', icon: 'ph-clipboard-text' },
  { key: 'FILES', label: 'File Attachments', icon: 'ph-file-arrow-up' },
  { key: 'SUMMARY', label: 'Lookups & Metadata', icon: 'ph-info' }
];

export function getCommonTestItems(context: TestContextIds): DetailedTestItem[] {
  return [
    // ==================== 1. ALERTS & NOTIFICATIONS ====================
    {
      id: 'COM-ALT-1',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get Application Types',
      endpoint: 'api/AlertsAndNotifications/GetApplicationTypes?ModuleId=1&RecordID=-1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of application types or valid response payload',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-2',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get AN Placeholders',
      endpoint: 'api/AlertsAndNotifications/GetANPlaceHolders/1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of placeholder tags for notifications',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-3',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get Notification & Alert Events',
      endpoint: 'api/AlertsAndNotifications/GetANNotificationAndAlertEvents/1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of available trigger events',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-4',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get Outgoing SMTP Email Servers',
      endpoint: 'api/AlertsAndNotifications/GetANOutgoingSMTPEmailServers/1',
      method: 'GET',
      payload: null,
      expectedData: 'List of configured SMTP email servers',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-5',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get Alerts & Notifications Summary',
      endpoint: 'api/AlertsAndNotifications/GetAlertsAndNotificationsSummary/1',
      method: 'GET',
      payload: null,
      expectedData: 'Summary list of alerts rules',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-6',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get Alert Rule By ID',
      endpoint: 'api/AlertsAndNotifications/GetAlertsAndNotificationsById/1/1',
      method: 'GET',
      payload: null,
      expectedData: 'Single alert configuration model',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-7',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Save Alerts & Notifications Rule',
      endpoint: 'api/AlertsAndNotifications/SaveAlertsAndNotifications',
      method: 'POST',
      payload: {
        ModuleId: '1',
        Name: 'Auto Test Alert Rule',
        TargetUser: 'Admin',
        ANType: 'Email',
        NotificationEventID: '1',
        AlertEventID: '1',
        EventDays: 1,
        IsEmailAlert: true,
        ToAddress: 'test@medrion.com',
        Subject: 'Automated Test Notification',
        IsSystemNotification: true
      },
      expectedData: 'Save status confirmation object',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-8',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Save Outgoing SMTP Assignment',
      endpoint: 'api/AlertsAndNotifications/SaveOutgoingSMTPEmail/1/1',
      method: 'GET',
      payload: null,
      expectedData: 'Assignment confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-9',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get User Notifications',
      endpoint: 'api/Notifications/GetUserNotifications',
      method: 'GET',
      payload: null,
      expectedData: 'List of in-app notifications for active user',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-ALT-10',
      category: 'ALERTS',
      categoryLabel: 'Alerts & Notifications',
      apiName: 'Get Notification Count',
      endpoint: 'api/Notifications/NotificationCount',
      method: 'GET',
      payload: null,
      expectedData: 'Integer or count wrapper object of unread notifications',
      status: 'PENDING',
      matched: false
    },

    // ==================== 2. CRITERIA & DYNAMIC SCREEN RESPONSE ====================
    {
      id: 'COM-CRT-1',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Get Modules List',
      endpoint: 'api/CommonCriteria/GetModules',
      method: 'GET',
      payload: null,
      expectedData: 'Array of system modules',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-2',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Get Screen List By Module',
      endpoint: 'api/CommonCriteria/GetScreenList?ModuleId=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of screens in module',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-3',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Get Screen List Advanced Search',
      endpoint: 'api/CommonCriteria/GetScreenListAdvance',
      method: 'POST',
      payload: { ModuleId: '1', ScreenName: '' },
      expectedData: 'Filtered screens list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-4',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Fetch Screen Controls',
      endpoint: 'api/CommonCriteria/FetchScreenControls?screenId=1&subScreenId=0',
      method: 'GET',
      payload: null,
      expectedData: 'Dynamic form controls metadata',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-5',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Fetch Extended Controls',
      endpoint: 'api/CommonCriteria/FetchExtendedControls?screenId=1&subScreenId=0',
      method: 'GET',
      payload: null,
      expectedData: 'Extended controls configuration',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-6',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Fetch Response Controls',
      endpoint: 'api/CommonCriteria/FetchResponseControls?screenId=1&subScreenId=0',
      method: 'GET',
      payload: null,
      expectedData: 'Response controls definitions',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-7',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Get Screen Controls List',
      endpoint: 'api/CommonCriteria/GetScreenControlsList?screenId=1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of screen form controls',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-8',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Get Screen Response Data',
      endpoint: 'api/CommonCriteria/GetScreenResponse',
      method: 'POST',
      payload: { ScreenId: '1', ApplicationId: '1' },
      expectedData: 'Saved screen responses object',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-9',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Get Screen Response Row',
      endpoint: 'api/CommonCriteria/GetScreenResponseRow',
      method: 'POST',
      payload: { ScreenId: '1', ApplicationId: '1', RowId: '1' },
      expectedData: 'Single row screen response data',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-10',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Get Extended Screen Response',
      endpoint: 'api/CommonCriteria/GetExtendedScreenResponse?ScreenId=1&ApplicationId=1',
      method: 'GET',
      payload: null,
      expectedData: 'Extended screen values list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-CRT-11',
      category: 'CRITERIA',
      categoryLabel: 'Screen Controls & Response',
      apiName: 'Save User Preferences Columns',
      endpoint: 'api/CommonCriteria/SaveUserPreferencesColumns',
      method: 'POST',
      payload: { UserID: '1', ScreenName: 'IST_GRID', Columns: ['ID', 'NAME', 'STATUS'] },
      expectedData: 'Saved user column preference confirmation',
      status: 'PENDING',
      matched: false
    },

    // ==================== 3. REVIEW WORKFLOW ====================
    {
      id: 'COM-REV-1',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Reviews Summary',
      endpoint: 'api/Review/GetReviews?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of review workflow rounds for application',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-2',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Review Types',
      endpoint: 'api/Review/GetReviewTypes?ModuleID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Review type options (Internal, Scientific, Budget)',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-3',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get My Reviews Grid',
      endpoint: 'api/Review/MyReviews',
      method: 'POST',
      payload: { Status: 'ALL', PageIndex: 1, PageSize: 10 },
      expectedData: 'List of reviews assigned to current user',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-4',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get My Reviews Count',
      endpoint: 'api/Review/MyReviewsCount?isOwner=false',
      method: 'GET',
      payload: null,
      expectedData: 'Count of pending reviews',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-5',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Reviewable Documents',
      endpoint: 'api/Review/GetDocuments?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of documents attached for review',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-6',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Review Documents By ReviewID',
      endpoint: 'api/Review/GetReviewDocuments?ReviewId=1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of review document links',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-7',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Review Doc Details By ID',
      endpoint: 'api/Review/ReviewDocments?Id=1',
      method: 'GET',
      payload: null,
      expectedData: 'Detailed review document descriptor',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-8',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Available Review Users',
      endpoint: 'api/Review/GetUsers?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of potential reviewers',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-9',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Review Owner',
      endpoint: 'api/Review/GetOwner?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Owner details object',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-10',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Get Change Owner Permissions',
      endpoint: 'api/Review/GetChangeOwnPr?Module=1',
      method: 'GET',
      payload: null,
      expectedData: 'Permission indicators for ownership transfer',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-11',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Edit Review Details',
      endpoint: 'api/Review/EditReview?Id=1',
      method: 'GET',
      payload: null,
      expectedData: 'Review model for editing',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-12',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Check Reviewer Before Start',
      endpoint: 'api/Review/CheckReviwerBeforeStart?AppId=1',
      method: 'GET',
      payload: null,
      expectedData: 'Validation status check response',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-13',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Insert Review Workflow',
      endpoint: 'api/reviews/insert',
      method: 'POST',
      payload: { ApplicationID: '1', REVIEW_NAME: 'Scientific Advisory Review', STATUS: '1' },
      expectedData: 'Created review confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-14',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Update Review Workflow',
      endpoint: 'api/reviews/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', REVIEW_NAME: 'Scientific Review (Round 2)' },
      expectedData: 'Updated review confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-15',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Delete Review',
      endpoint: 'api/reviews/delete/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete review confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-16',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Start Review Workflow',
      endpoint: 'api/reviews/start?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Started review confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-17',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Cancel Review Workflow',
      endpoint: 'api/reviews/cancel?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Cancelled review confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-18',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Change Owner Review',
      endpoint: 'api/reviews/changeowner',
      method: 'POST',
      payload: { RecordID: '1', NEW_OWNER_ID: '1' },
      expectedData: 'Changed owner confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-19',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Update Reviewer Status',
      endpoint: 'api/reviews/updatestatus',
      method: 'POST',
      payload: { ReviewerID: '1', STATUS: 'APPROVED', COMMENTS: 'Approved with minor remarks' },
      expectedData: 'Updated status confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-REV-20',
      category: 'REVIEW',
      categoryLabel: 'Review Workflow',
      apiName: 'Update Reviewers Order',
      endpoint: 'api/reviews/updateorder',
      method: 'POST',
      payload: { ReviewID: '1', OrderList: [{ ReviewerID: '1', Order: 1 }] },
      expectedData: 'Updated order confirmation',
      status: 'PENDING',
      matched: false
    },

    // ==================== 4. FILE ATTACHMENTS ====================
    {
      id: 'COM-FIL-1',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Get Attachment Classifications',
      endpoint: 'api/ISTFileAttachments/GetAttachClass?ModuleName=IST',
      method: 'GET',
      payload: null,
      expectedData: 'Array of attachment classification categories',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-2',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Get Attachment Application Types',
      endpoint: 'api/ISTFileAttachments/GetApplicationTypes?moduleID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Array of module application types',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-3',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Get Screen Names For Attachments',
      endpoint: 'api/ISTFileAttachments/GetScreenNames?MODULE_ID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of screens mapped for attachment uploads',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-4',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Get Attachments Summary',
      endpoint: 'api/ISTFileAttachments/getAttachmentsSummary?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Summary list of files for application',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-5',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Search Attachments Grid',
      endpoint: 'api/ISTFileAttachments/getAttachmentsSearch',
      method: 'POST',
      payload: { ApplicationID: '1', PageIndex: 1, PageSize: 10 },
      expectedData: 'Search result dataset of attachments',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-6',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Get Screen Attachments By Transaction',
      endpoint: 'api/ISTFileAttachments/getScreenAttachments?TransactionID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of transaction-level file attachments',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-7',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Get Attachment Master Data',
      endpoint: 'api/ISTFileAttachments/GetMasterData',
      method: 'GET',
      payload: null,
      expectedData: 'Master dropdowns for attachments configuration',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-8',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Get Feature Documents',
      endpoint: 'api/screen/getfeaturedocuments',
      method: 'GET',
      payload: null,
      expectedData: 'List of feature guideline & template documents',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-9',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Insert Attachment',
      endpoint: 'api/CommonFile/InsertgrtSposUploadDoc',
      method: 'POST',
      payload: { ApplicationID: '1', FILE_NAME: 'Protocol_Document.pdf', FILE_SIZE: '1024' },
      expectedData: 'Created attachment confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-10',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Update Attachment Details',
      endpoint: 'api/CommonFile/UpdategrtSposUploadDoc',
      method: 'POST',
      payload: { RecordID: '1', FILE_DESCRIPTION: 'Updated Protocol Document' },
      expectedData: 'Updated attachment confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-11',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Delete File Attachment',
      endpoint: 'api/CommonFile/deletefile/9999',
      method: 'GET',
      payload: null,
      expectedData: 'Delete file confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-FIL-12',
      category: 'FILES',
      categoryLabel: 'File Attachments',
      apiName: 'Edit Template Details',
      endpoint: 'api/CommonFile/EditTemplateDetails?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Template details descriptor',
      status: 'PENDING',
      matched: false
    },

    // ==================== 5. MASTER LOOKUPS & METADATA ====================
    {
      id: 'COM-SUM-1',
      category: 'SUMMARY',
      categoryLabel: 'Lookups & Metadata',
      apiName: 'Get Prefix / Salutation Lookups',
      endpoint: 'api/appuser/getPrefixlkps/DEFAULT',
      method: 'GET',
      payload: null,
      expectedData: 'Array of prefix options (Mr., Dr., Prof., etc.)',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-SUM-2',
      category: 'SUMMARY',
      categoryLabel: 'Lookups & Metadata',
      apiName: 'Get States Summary',
      endpoint: 'api/state/SummaryData?moduleId=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of state & territory codes',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-SUM-3',
      category: 'SUMMARY',
      categoryLabel: 'Lookups & Metadata',
      apiName: 'Get State By ID',
      endpoint: 'api/state/getstatebyid/1',
      method: 'GET',
      payload: null,
      expectedData: 'State record descriptor',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-SUM-4',
      category: 'SUMMARY',
      categoryLabel: 'Lookups & Metadata',
      apiName: 'Fetch IEG Build Version',
      endpoint: 'api/appuser/fetchiegbuildversion',
      method: 'GET',
      payload: null,
      expectedData: 'System build & release version string/object',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-SUM-5',
      category: 'SUMMARY',
      categoryLabel: 'Lookups & Metadata',
      apiName: 'Get Policy Version Details',
      endpoint: 'api/screen/PolicyVersionDetails?moduleCode=IST',
      method: 'GET',
      payload: null,
      expectedData: 'Active policy version information',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'COM-SUM-6',
      category: 'SUMMARY',
      categoryLabel: 'Lookups & Metadata',
      apiName: 'Save Feature Documents',
      endpoint: 'api/CommonSummary/SaveFeatureDocuments',
      method: 'POST',
      payload: { FeatureId: '1', DocumentName: 'User_Manual.pdf' },
      expectedData: 'Saved feature document confirmation',
      status: 'PENDING',
      matched: false
    }
  ];
}
