import { CategoryTab, DetailedTestItem, TestContextIds } from './test-services.types';

export const IST_CATEGORIES: CategoryTab[] = [
  { key: 'ALL', label: 'All IST APIs', icon: 'ph-squares-four' },
  { key: 'GENERAL', label: 'General Info & Apps', icon: 'ph-article' },
  { key: 'STUDY_TEAM', label: 'Study Team & IRB', icon: 'ph-users-three' },
  { key: 'ACTIVITIES', label: 'Activities & Pubs', icon: 'ph-newspaper' },
  { key: 'REQUESTS', label: 'Requests & Reports', icon: 'ph-git-pull-request' }
];

export function getIstTestItems(context: TestContextIds): DetailedTestItem[] {
  return [
    // ==================== 1. GENERAL INFO & APPLICATIONS ====================
    {
      id: 'IST-GEN-1',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get Applications List',
      endpoint: 'api/ISTGeneralInfo/GetApplicationsList',
      method: 'POST',
      payload: { Status: 'ALL', PageIndex: 1, PageSize: 10 },
      expectedData: 'Array of IST applications',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-2',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Summary Search Applications',
      endpoint: 'api/ISTGeneralInfo/getSummarySearch',
      method: 'POST',
      payload: { SearchText: '', Status: '-1' },
      expectedData: 'Filtered applications summary list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-3',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get Master Dropdown Data',
      endpoint: 'api/ISTGeneralInfo/GetMasterList?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Master dropdowns for IST general form',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-4',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get My Applications List',
      endpoint: 'api/ISTMyApplications/GetMyApplicationsList',
      method: 'POST',
      payload: { PageIndex: 1, PageSize: 10 },
      expectedData: 'User-specific IST applications',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-5',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Search My Applications',
      endpoint: 'api/ISTMyApplications/getMySummarySearch',
      method: 'POST',
      payload: { SearchText: '' },
      expectedData: 'Filtered personal applications',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-6',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Get Application Change Log',
      endpoint: 'api/ISTGeneralInfo/GetApp_ChangeLog?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Audit change log history',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-7',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Validate Application Submission',
      endpoint: 'api/ISTGeneralInfo/IST_APPSubmitValidation?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Submission validation status or error list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-8',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Insert IST General Info',
      endpoint: 'api/istgeneralinfo/insert',
      method: 'POST',
      payload: { APPLICATION_NAME: 'IST Oncology Study Phase II', STATUS: '1' },
      expectedData: 'Created general info confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-9',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Update IST General Info',
      endpoint: 'api/istgeneralinfo/update',
      method: 'POST',
      payload: { APPLICATION_ID: '1', APPLICATION_NAME: 'IST Oncology Study Phase II (Updated)' },
      expectedData: 'Updated general info confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-GEN-10',
      category: 'GENERAL',
      categoryLabel: 'General Info & Apps',
      apiName: 'Insert IST Organization Mapping',
      endpoint: 'api/ISTOrganization/Insert',
      method: 'POST',
      payload: { APPLICATION_ID: '1', ORGANIZATION_ID: '1' },
      expectedData: 'Saved organization association',
      status: 'PENDING',
      matched: false
    },

    // ==================== 2. STUDY TEAM & IRB ====================
    {
      id: 'IST-STM-1',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Get Study Team Master Data',
      endpoint: 'api/ISTStudyTeam/GetMasterData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Master roles & org dropdowns for study team',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-2',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Search Study Team Master Data',
      endpoint: 'api/ISTStudyTeam/GetMasterDataSearch?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Search master records for study team',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-3',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Get Study Team Summary Data',
      endpoint: 'api/ISTStudyTeam/GetSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of study team members',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-4',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Search Study Team Members',
      endpoint: 'api/ISTStudyTeam/GetSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered study team member records',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-5',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Edit Study Team Member',
      endpoint: 'api/ISTStudyTeam/edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study team record details for editing',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-6',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Insert Study Team Member',
      endpoint: 'api/iststudyteam/insert',
      method: 'POST',
      payload: { ApplicationID: '1', USER_NAME: 'Dr. Sarah Connor', ROLE_ID: '1' },
      expectedData: 'Created study team member confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-7',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Update Study Team Member',
      endpoint: 'api/iststudyteam/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', USER_NAME: 'Dr. Sarah Connor' },
      expectedData: 'Updated study team confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-8',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Get Review Board Summary Data',
      endpoint: 'api/ISTReviewBoard/GetSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Review board / IRB details for application',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-9',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Insert Review Board',
      endpoint: 'api/istreviewboard/insert',
      method: 'POST',
      payload: { ApplicationID: '1', BOARD_NAME: 'Institutional Review Board' },
      expectedData: 'Created review board record',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-STM-10',
      category: 'STUDY_TEAM',
      categoryLabel: 'Study Team & IRB',
      apiName: 'Update Review Board',
      endpoint: 'api/istreviewboard/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', BOARD_NAME: 'IRB Ethics Committee' },
      expectedData: 'Updated review board record',
      status: 'PENDING',
      matched: false
    },

    // ==================== 3. ACTIVITIES & PUBLICATIONS ====================
    {
      id: 'IST-ACT-1',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Get Activities Summary Data',
      endpoint: 'api/ISTActivitiesseminars/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Trial activities & seminars list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-ACT-2',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Get Activities Master Drop Data',
      endpoint: 'api/ISTActivitiesseminars/GetMasterDropData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Activity master options',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-ACT-3',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Search Activities Summary',
      endpoint: 'api/ISTActivitiesseminars/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered activities list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-ACT-4',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Get Publications Summary Data',
      endpoint: 'api/ISTPublications/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of publications for trial',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-ACT-5',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Get Publications Master Drop Data',
      endpoint: 'api/ISTPublications/GetMasterDropData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Publication master dropdown values',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-ACT-6',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Search Publications Summary',
      endpoint: 'api/ISTPublications/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered publications list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-ACT-7',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Get Site Evaluation Summary',
      endpoint: 'api/ISTSiteevaluation/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Site evaluation summary details',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-ACT-8',
      category: 'ACTIVITIES',
      categoryLabel: 'Activities & Pubs',
      apiName: 'Search Site Evaluation Summary',
      endpoint: 'api/ISTSiteevaluation/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered site evaluation list',
      status: 'PENDING',
      matched: false
    },

    // ==================== 4. REQUESTS, MILESTONES & REPORTS ====================
    {
      id: 'IST-REQ-1',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Requests Summary Master',
      endpoint: 'api/ISTAllRequests/GetSummaryMaster?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Requests summary master metadata',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-2',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Requests Summary Data',
      endpoint: 'api/ISTAllRequests/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Summary of drug / fund requests',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-3',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Search Requests Summary',
      endpoint: 'api/ISTAllRequests/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered request list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-4',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Product Master Drop Data',
      endpoint: 'api/ISTAllRequests/GetProductMasterDropData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Product request options',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-5',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Fund Master Drop Data',
      endpoint: 'api/ISTAllRequests/GetFundMasterDropData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Fund request options',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-6',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Insert Product Request',
      endpoint: 'api/istallrequests/insertproduct',
      method: 'POST',
      payload: { ApplicationID: '1', PRODUCT_ID: '1', QUANTITY: 50 },
      expectedData: 'Created product request confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-7',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Update Product Request',
      endpoint: 'api/istallrequests/updateproduct',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', QUANTITY: 80 },
      expectedData: 'Updated product request confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-8',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Edit Product Request',
      endpoint: 'api/ISTAllRequests/EditProduct?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Product request record for editing',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-9',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Insert Fund Request',
      endpoint: 'api/istallrequests/insertfund',
      method: 'POST',
      payload: { ApplicationID: '1', AMOUNT: 40000, CURRENCY_ID: 'USD' },
      expectedData: 'Created fund request confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-10',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Update Fund Request',
      endpoint: 'api/istallrequests/updatefund',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', AMOUNT: 45000 },
      expectedData: 'Updated fund request confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-11',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Approve Request Workflow',
      endpoint: 'api/ISTAllRequests/Approve?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Approval result confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-12',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Reject Request Workflow',
      endpoint: 'api/istallrequests/reject?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Rejection confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-13',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Allocate Request Workflow',
      endpoint: 'api/ISTAllRequests/Allocate?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Allocation result confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-14',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Return Request Workflow',
      endpoint: 'api/istallrequests/requestreturn?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Return request confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-15',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Withdraw Request Workflow',
      endpoint: 'api/istallrequests/withdraw?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Withdrawal confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-16',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Close Request Workflow',
      endpoint: 'api/istallrequests/close?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Close confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-17',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Milestones Summary Data',
      endpoint: 'api/ISTMilestones/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Milestone tracking list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-18',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Search Milestones Summary',
      endpoint: 'api/ISTMilestones/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered milestones list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-19',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Edit Milestone',
      endpoint: 'api/ISTMilestones/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Milestone record for editing',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-20',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Insert Milestone',
      endpoint: 'api/istmilestones/insert',
      method: 'POST',
      payload: { ApplicationID: '1', MILESTONE_NAME: 'Protocol IRB Approval', STATUS: '1' },
      expectedData: 'Created milestone confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-21',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Update Milestone',
      endpoint: 'api/istmilestones/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', MILESTONE_NAME: 'Protocol IRB Approval (Updated)' },
      expectedData: 'Updated milestone confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-22',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Study Reports Summary Data',
      endpoint: 'api/ISTStudyreports/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study reports submission records',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-23',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Study Reports Master Data',
      endpoint: 'api/ISTStudyreports/GetMasterData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study report master dropdowns',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-24',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Search Study Reports Summary',
      endpoint: 'api/ISTStudyreports/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered study reports list',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-25',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Edit Study Report',
      endpoint: 'api/ISTStudyreports/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Study report record for editing',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-26',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Insert Study Report',
      endpoint: 'api/iststudyreports/insert',
      method: 'POST',
      payload: { ApplicationID: '1', REPORT_TYPE: 'Interim Safety Report', STATUS: '1' },
      expectedData: 'Created study report confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-27',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Update Study Report',
      endpoint: 'api/iststudyreports/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', REPORT_TYPE: 'Final Safety Report' },
      expectedData: 'Updated study report confirmation',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-28',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Amendments Summary',
      endpoint: 'api/ISTAmendments/getSummaryData?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'List of protocol amendments',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-29',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Get Amendments Types',
      endpoint: 'api/ISTAmendments/getTypes?ApplicationID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Amendment type definitions',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-30',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Search Amendments Summary',
      endpoint: 'api/ISTAmendments/getSummarySearchData',
      method: 'POST',
      payload: { ApplicationID: '1' },
      expectedData: 'Filtered amendments records',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-31',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Edit Amendment',
      endpoint: 'api/ISTAmendments/Edit?RecordID=1',
      method: 'GET',
      payload: null,
      expectedData: 'Amendment record for editing',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-32',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Insert Amendment',
      endpoint: 'api/istamendments/insert',
      method: 'POST',
      payload: { ApplicationID: '1', AMENDMENT_NAME: 'IST Protocol Amendment v1', REASON: 'Sample Size Increase' },
      expectedData: 'Created amendment record',
      status: 'PENDING',
      matched: false
    },
    {
      id: 'IST-REQ-33',
      category: 'REQUESTS',
      categoryLabel: 'Requests & Reports',
      apiName: 'Update Amendment',
      endpoint: 'api/istamendments/update',
      method: 'POST',
      payload: { RecordID: '1', ApplicationID: '1', AMENDMENT_NAME: 'IST Protocol Amendment v1.1' },
      expectedData: 'Updated amendment record',
      status: 'PENDING',
      matched: false
    }
  ];
}
